services:
  iris:
    build:
      context: ./src-iris
      dockerfile: Dockerfile
      args:
        IRIS_IMAGE: containers.intersystems.com/intersystems/irishealth-community
        IRIS_TAG: 2024.3
        IRIS_PASSWORD: ${IRIS_PASSWORD}
        MONGO_CREDENTIALS: ${MONGO_CREDENTIALS}
        MONGO_URI: ${DB_CONECTION_STRING}
    ports:
      - "8082:80"
    volumes:
      - ./volumes/iris:/iris-shared
    secrets:
      - iris_pw

secrets:
  iris_pw:
    file: ./src-iris/irispw.txt