version: '3.8'

services:
  iris:
    build:
      context: ./src-iris
      args:
        IRIS_IMAGE: "${IRIS_IMAGE}"
        IRIS_TAG: "${IRIS_IMAGE_TAG}"
    volumes:
      - ./volumes/iris:/iris-shared
      - ./src-iris/irispw.txt:/run/secrets/iris_pw  # Montando o arquivo de senha diretamente no container
    environment:
      - IRIS_PASSWORD=${IRIS_PASSWORD}  # Se necessário, passe a senha também como variável de ambiente
    # command:
    # - "${LICENSE_KEY_FILE:+--key /iris-shared/${LICENSE_KEY_FILE}}"

  webgateway:
    image: ${WG_IMAGE}:${WG_IMAGE_TAG}
    ports:
      - "${WEBSERVER_PORT}:80"
    environment:
      - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
      - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
      - ./volumes/webgateway:/webgateway-shared
      - ./src-iris/irispw.txt:/run/secrets/iris_pw  # Montando o arquivo de senha para o webgateway também

secrets:
  iris_pw:
    external: true  # Use isso apenas se estiver usando Docker Swarm e Secrets nativos
